title: WebShop
description: Towards Scalable Real-World Web Interaction with Grounded Language Agents
env_repo: https://github.com/princeton-nlp/WebShop
mdl_repo: # To do
paper: https://arxiv.org/abs/2207.01206
live: http://3.83.245.205:3000/pnlp
twitter:
  username: princeton_nlp
  title_image: https://avatars.githubusercontent.com/u/44678448?s=280&v=4
authors:
  - name: Shunyu Yao
    link: https://ysymyth.github.io/
    pic: https://ysymyth.github.io/images/self.jpeg
  - name: Howard Chen
    link: https://howard50b.github.io/
    pic: https://www.cs.princeton.edu/~danqic/images/members/howard_chen.jpg
  - name: John Yang
    link: https://john-b-yang.github.io/
    pic: https://john-b-yang.github.io/static/profpic.jpg
  - name: Karthik Narasimhan
    link: https://www.cs.princeton.edu/~karthikn/
    pic: https://princeton-nlp.github.io/assets/images/people/karthik-photo.jpg
